# Refer to https://djlint.com/docs/linter/

profile = "jinja"

blank_line_after_tag = "load,extends,include,block"
blank_line_before_tag="load,extends,include,block"
close_void_tags=true
extend_exclude = ".venv,venv,node_modules"
format_js = true
indent = 2
line_break_after_multiline_tag=true
max_attribute_length=6
max_blank_lines=2
max_line_length = 150
use_gitignore=true

include = "H017,H035"
ignore = "D004,D018,H006,H013"
